config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end


    # get "tasks" => "tasks#index" // tous les restaus
    # get "tasks/:id" => "tasks#show" // un restau en particulier
    # get "tasks/new" => "tasks#new" // creer un restaurant etape 1
    # post "tasks" => "tasks#create" // creer un restaurant etape 2
    # get "tasks/:id/edit" => "tasks#edit" // updater un restaurant etape 1 // edit pour ne pas avoir de conflit avec le show
    # patch "tasks" => "tasks#update" // updater un restaurant etape 2
    # delete "tasks/:id" => "tasks#delete" // supprimer une task

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1> My tasks </h1>

<% @tasks.each do |task| %>
   <p><%= link_to task.title, task_path(task)%></p>
   <% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

<form class="new_task" id="new_task" action="/tasks" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token">
  <label for="task_name">Title</label>
  <input type="text" name="task[title]" id="task_name">
  <label for="task_address">Details</label>
  <input type="text" name="task[details]" id="task_details">
  <label for="task_completed">Completed ?</label>
  <input type="number" name="task[completed]" id="task_completed">
  <input type="checkbox" name="commit" value="Create Task" data-disable-with="Create Task">
</form>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<p><%= link_to "revenir à toutes mes tasks", tasks_path %></p>